### ISSUE TITLE
Update “Version Date Range” to “Publication Date Range”

### ISSUE THREAD

**Issue by downiec** [esgf2-us/metagrid#283]
#### Describe the solution you'd like

Update “Version Date Range” to “Publication Date Range” depending on the context of which project is selected.
Some projects 'Version Date Range' is appropriate, and for some it's better to show 'Publication Date Range'.

-Figure out how to determine which label to use, based on what project is selected.

**Comment by sashakames** [comment]
The "version" attribute is in date format for most projects.  Eg for E3SM - need to change the search widget to not use a calendar.
For "publication date" - for E3SM we need to add &from=&to=  and convert to the proper Solr ISO dates.  This could be a separate issue.

**Comment by sashakames** [comment]
what we need is a conditional for projects that don't use the vYYYYMMDD format.  eg E3SM = false, CMIP6, etc = true
