### ISSUE TITLE
Wget script tranfser won't work

### ISSUE THREAD

**Issue by DaisyShi19** [esgf2-us/metagrid#614]
Hello all,
I am trying to generate the wget script for multiple variables for one specific models. When I selected target datasets in the cart, selected "Wget", and clicked on "Transfer", it doesn't work. 

I tried it on Macbook and PC, with multiple browsers. It usually work for the first time using the browser, then it stopped working.
I tried restart the browser, clear the cache, it still won't work.
Tried restart the computer, still doesn't work.

Any help is appreciated.
Thanks!

**Comment by sashakames** [comment]
Hello @DaisyShi19 , I can help investigate this issue but would like some more information.
(1) confirm you are using https://aims2.llnl.gov/ (the other site is for testing and not stable)
(2) can you be more specific, what search (use the Copy Search feature and paste that) produces your datasets?
(3) how many datasets were a problem with the wget generation?

I did a quick test of my data cart and the script generated for me on two attempts, second with 100 datasets in the cart, so this is something more specific.

**Comment by DaisyShi19** [comment]
Thank you Sasha. I confirm that I am using the https://aims2.llnl.gov/ site. Yes, I used the Copy Search feature and paste that to produce my datasets. The request is for 18 datasets (82 files, 75GB).

I noticed that when I signed off my ESGF account, it was able to generate the wget script. Is it something related to account restrictions, e.g., limited requests per account?


> Hello @DaisyShi19 , I can help investigate this issue but would like some more information. (1) confirm you are using https://aims2.llnl.gov/ (the other site is for testing and not stable) (2) can you be more specific, what search (use the Copy Search feature and paste that) produces your datasets? (3) how many datasets were a problem with the wget generation?
> 
> I did a quick test of my data cart and the script generated for me on two attempts, second with 100 datasets in the cart, so this is something more specific.

**Comment by sashakames** [comment]
@DaisyShi19 could you please paste the search here so I may take a look?  That is interesting to know that script fails when you are signed in, that is another clue...  There is no intended restriction ;  we are looking for something out of the ordinary that would cause a reproducible failure.

**Comment by DaisyShi19** [comment]
Hi Sasha, thanks again. I tried logging in and it works now (both logging in and out) with safari on Mac and Chrome on PC. 

I didn't make any changes to my computers or browser settings. But it was having issues last week. 

I can close the issue for now. Do you have any idea why just in case the issue came back again?

**Comment by sashakames** [comment]
Hi, if we can reproduce synchronization issues that happen with old sessions, we might be able to fix this, otherwise logout/login will have to serve as the workaround.
