### ISSUE TITLE
Unable to combine items and download wget

### ISSUE THREAD

**Issue by Yiyu-Zheng** [esgf2-us/metagrid#615]
I've added 4 data files from FGOALS-f3-L to my chart, the name of the files are listed below: 
CMIP6.CMIP.CAS.FGOALS-f3-L.abrupt-4xCO2.r1i1p1f1.Amon.uas.gr
CMIP6.CMIP.CAS.FGOALS-f3-L.piControl.r1i1p1f1.Amon.uas.gr
CMIP6.CMIP.CAS.FGOALS-f3-L.piControl.r1i1p1f1.Amon.vas.gr
CMIP6.CMIP.CAS.FGOALS-f3-L.abrupt-4xCO2.r1i1p1f1.Amon.vas.gr

The data node is esgf-data1.llnl.gov.

I'd like to combine all 4 files and generate one wget file. But after I select all items and click download, nothing happens.
When I use the download button in each row of each data file, it works.
Yesterday, when I tried to combine files and download one wget file, it also worked.

I'm wondering how to make this combine & download working again..?

**Comment by sashakames** [comment]
Hi, Are you using Chrome or Firefox?  If so, could you try to open a Javascript console and either paste the error or take a screenshot?   Other browsers aren't supported, sorry for the inconvenience.

**Comment by Yiyu-Zheng** [comment]
I'm using Chrome, here's the screenshot
![屏幕快照 2024-03-04 的 11 12 15 上午](https://github.com/esgf2-us/metagrid/assets/61731973/f0c7889a-1078-40c7-80ee-182367824fce)

**Comment by sashakames** [comment]
Are you logged in?  Perhaps try to log out and log in again...

**Comment by Yiyu-Zheng** [comment]
Yes, I was logged in before, logging out and back works! Many thanks!!
