### ISSUE TITLE
" No ESG Credentials found in /home/ramoking/.esg/credentials.pem"

### ISSUE THREAD

**Issue by Ramoking90** [esgf2-us/metagrid#617]
### Describe the bug

**Desktop (please complete the following information):**
Windows 10
- OS:

- Browser and Version: Version 122.0.6261.95 (Official Build) (64-bit)

#### To Reproduce

1.

**Comment by sashakames** [comment]
Please use `bash wget-XXX.sh -s` this disables the need for credentials. 
The platform will migrate soon to an upgraded version of the wget script that no longer will assume the need for credentials as the requirement is deprecated.
