### ISSUE TITLE
esgf-ictp.hpc.cineca.it server down

### ISSUE THREAD

**Issue by pnnl-sun** [esgf2-us/metagrid#620]
Hi, we are trying to pull some Cordex data from the esgf-ictp.hpc.cineca.it server, but it has been down since at least the middle of last week. Just wondering if you know when the server might come back up, or if the data is replicated/available somewhere else? Thank you!

**Comment by sashakames** [comment]
Hello @pnnl-sun , please write to esgf-user@llnl.gov.  Github issues for this repo are for UI issues faced Metagrid, eg. something isn't working as expected.  Thank you!
