### ISSUE TITLE
The requested resource at the ESGF wget API service was invalid. Please contact support.

### ISSUE THREAD

**Issue by OsakaH09** [esgf2-us/metagrid#627]
OS: Windows 10
Browser: Microsoft Edge

1. Add the file to cart
2. Trying to download the .sh file with wget, and reported the following error in the picture

![QQ图片20240402092710](https://github.com/esgf2-us/metagrid/assets/86279055/b3d697aa-7bc2-4391-a452-461e5e567250)

**Comment by sashakames** [comment]
There was an outage of services at LLNL but these have been restored now.

**Comment by OsakaH09** [comment]
Thanks for your reply, it has indeed been fixed.



Best Wishes.




Yours sincerely.













在 2024-04-03 02:35:55，"Sasha Ames" ***@***.***> 写道：

There was an outage of services at LLNL but these have been restored now.
