### ISSUE TITLE
There was an issue fetching search results. Please contact support or try again later.

### ISSUE THREAD

**Issue by HuaiyuWEI** [esgf2-us/metagrid#628]
### Describe the bug

**Desktop (please complete the following information):**

- OS: Windows 11

- Browser and Version: Edge

#### To Reproduce
1. Go to 'https://aims2.llnl.gov/search'
2. Click on 'the blue icon to the right of CMIP6'
3. See error

![image](https://github.com/esgf2-us/metagrid/assets/99250400/c58d7a24-968c-4256-8b90-a88b98dd9175)

**Comment by sashakames** [comment]
Search is restored now sorry for the inconvenience.

**Comment by 123book321** [comment]
> Search is restored now sorry for the inconvenience.

The same problem emerged again.

**Comment by Daiyi0511** [comment]
> Search is restored now sorry for the inconvenience.

This problem happened again， please tell me how to handle it

![Image](https://github.com/user-attachments/assets/3c15fcef-88c4-4890-a159-3136e2165a48)

**Comment by gitte666** [comment]
Please help me solve the same problem. It's very urgent. Thanks

**Comment by Pray0925** [comment]
The same problem emerged again.

**Comment by sashakames** [comment]
We are aware of the issue and a team is working on a solution.

**Comment by sashakames** [comment]
Search restored.  Please refresh your browser tab.

**Comment by fengziheng0920-netizen** [comment]
> Search restored. Please refresh your browser tab.
The same problem has frequently occurred this week.Please help me resolve it. Thanks.

<img width="1912" height="948" alt="Image" src="https://github.com/user-attachments/assets/3eb68a6f-32b6-43c4-b4e3-a3ca35571ec4" />
