### ISSUE TITLE
Federated Nodes link inactive

### ISSUE THREAD

**Issue by durack1** [esgf2-us/metagrid#631]
### Describe the bug

The "Federated Node" link in the current https://aims2.llnl.gov/ page links to https://www.esgf.io/nodes.html.
![Screenshot 2024-04-09 at 3 27 29 PM](https://github.com/esgf2-us/metagrid/assets/3229632/7100cbc8-ba84-44dd-9b49-1f053531a20e)

This link doesn't resolve

**Comment by sashakames** [comment]
Looping in @downiec

**Comment by sashakames** [comment]
`./components/NavBar/index.tsx:            href="https://www.esgf.io/nodes.html"`

**Comment by durack1** [comment]
@sashakames was there an intention of renaming the nodes aims2 -> esgf-node? If yes, that would be ideal, so we have that same template around the place esgf-node.someplace.somewhere

**Comment by sashakames** [comment]
Yeah, essentially that will be the effect once we migrate the production Metagrid environment to Nimbus.  `esgf-node` will be backed by Kubernetes.  `aims2` may hand around for pre-release, but we will be clear that its the case and suggest users go to production.

**Comment by sashakames** [comment]
I updated aims2.llnl.gov with the correct link.  Will keep issue open until the update is merged into the next release.
