### ISSUE TITLE
Failed to download EC-Earth3 data

### ISSUE THREAD

**Issue by Haiping008** [esgf2-us/metagrid#638]
Hi,
I tried to download some climate data on the esgf website 
https://esgf-data.dkrz.de/search/cmip6-dkrz/

I tried to download a single file manually and our IT staff tried to download the dataset (86 files) in the command.
But all failed (it shows 'couldn't download, network issue'). 
Could you help us with this issue?

The information is as follows:

Your browser and operating sytem
Google Chrome 124.0.6367.201 and Microsoft Edge for Business Version 124.0.2478.97 (both failed)
on Windows 10 version 22H2

Your OpenID.
https://esgf-data.dkrz.de/esgf-idp/openid/haiping.shen@ntnu.no

The complete name of the file(s) or data set(s) you attempt to download.
https://esgf.ichec.ie/thredds/fileServer/cmip6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r11i1p1f1/E3hr/sfcWind/gr/v20200201/sfcWind_E3hr_EC-Earth3_ssp245_r11i1p1f1_gr_205001010130-205012312230.nc

The host node, for instance, esgf-index1.ceda.ac.uk, esgf-node.llnl.gov,…
see above

The steps required to reproduce the problem.
$ curl -v https://esgf.ichec.ie/thredds/fileServer/cmip6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r11i1p1f1/E3hr/sfcWind/gr/v20200201/sfcWind_E3hr_EC-Earth3_ssp245_r11i1p1f1_gr_205001010130-205012312230.nc
* processing: https://esgf.ichec.ie/thredds/fileServer/cmip6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r11i1p1f1/E3hr/sfcWind/gr/v20200201/sfcWind_E3hr_EC-Earth3_ssp
245_r11i1p1f1_gr_205001010130-205012312230.nc
*   Trying 193.1.243.63:443...
* connect to 193.1.243.63 port 443 failed: Timed out
* Failed to connect to esgf.ichec.ie port 443 after 21091 ms: Couldn't connect to server
* Closing connection
curl: (28) Failed to connect to esgf.ichec.ie port 443 after 21091 ms: Couldn't connect to server

The exact error message. Run the script in debug mode to get a detailed error message:
see above

Thank you!

**Comment by sashakames** [comment]
Hi there, these issues are for reporting problems with the Metagrid web application, not data access.  Sorry for the misunderstanding!  If you have already emailed the esgf-user list, then someone will hopefully see the issue and can respond.  This appears to be an issue with the data hosted in Ireland.
