### ISSUE TITLE
"Unknown error" while downloading wget files

### ISSUE THREAD

**Issue by talbotos** [esgf2-us/metagrid#641]
### Describe the bug

**Desktop (please complete the following information):**

- OS: Windows 10

- Browser and Version: Google Chrome

#### To Reproduce

1. Go to https://esgf-dev1.llnl.gov/search
2. Select a file from the CMIP6 ensemble. In this case : CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp585.r1i1p1f1.day.hurs.gn, version 20190710
3. Select "wget" for download option
4. Press the download button
5. See error "An unknown error has occured"

#### Expected behavior

 Usually the download of the wget file is starting

#### Screenshots

 
![image](https://github.com/esgf2-us/metagrid/assets/170762005/c3d43140-5131-4047-9e53-76d6eaf525bf)

#### Additional context

 I tried : 1) different files and variables, 2) different browser, 3) different computer, 4) ask a friend to try with his own computer, but with the same result.

**Comment by sashakames** [comment]
Hi please try https://aims2.llnl.gov/

The url above in the issue description is the beta-test version of the site, so results are not guaranteed to work.  But we appreciate knowing there might be an issue.

**Comment by talbotos** [comment]
It worked well using your URL. Thank you very much for your help!

**Comment by RCHG** [comment]
This error is happening in my case very often. For example:

From [here](https://wcrp-cmip.org/cmip-phases/cmip7/cmip7-forcing-datasets/?__cf_chl_f_tk=LbjvM2jdWDe_WyGSKtAHC6yYhoDq3hMITzpK79hNz24-1782900371-1.0.1.1-EDGIiSVKgRThJ73ZFoyJztnL8LzQSPMFcm8kucMqELs
)
It is opening [this](https://input4mips-cvs.readthedocs.io/en/latest/dataset-overviews/)
Then I selected for example [one scenario](https://esgf-node.ornl.gov/search?project=input4MIPs&versionType=all&activeFacets=%7B%22source_id%22%3A%22IIASA-IAMC-m-1-1-1%22%7D).

It is opening this webpage and any attemp to download using wget gives this "Unknown error"

**Comment by sashakames** [comment]
@RCHG There is a problem with the ORNL site. Please use https://metagrid.esgf-west.org/ for wget generation
