### ISSUE TITLE
Failed in downloading CESM2 data

### ISSUE THREAD

**Issue by LangyaDavid** [esgf2-us/metagrid#644]
### Describe the bug

<I was trying to download 'snc' data in 'ssp245'. When I used the wget script, it returned 'no files'. Subsequently, I attempted to download the data file using the 'Download the data file with http.' button on ESGF Metagrid (ESGF MetaGrid (llnl.gov)). However, the website returned the following message:
"Hmm... Unable to access this page. The URL https://esgf-data.ucar.edu/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/NCAR/CESM2/ssp245/r11i1p1f1/day/snc/gn/v20200528/snc_day_CESM2_ssp245_r11i1p1f1_gn_20150101-20641231.nc may have an issue, or it may have been permanently moved to a new URL."
I encountered the same issue when trying to download other data such as ssp370 and ssp585. However, this problem did not occur when I selected other Source IDs like CanESM5. Therefore, I believe this issue might not be related to my local network.>

**Desktop (please complete the following information):**

- OS:Windows 10

- Browser and Version: Microsoft Edge Version 126.0.2592.61 (Official Build) (x86_64)

#### To Reproduce

1. Go to https://aims2.llnl.gov/search
2. Click on 'Source ID : CESM2'
3. Scroll down to 'CMIP6.ScenarioMIP.NCAR.CESM2.ssp245.r11i1p1f1.day.snc.gn'
4. Click on 'Download the data file with http.'
5. See error 'Hmm... Unable to access this page. The URL https://esgf-data.ucar.edu/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/NCAR/CESM2/ssp245/r11i1p1f1/day/snc/gn/v20200528/snc_day_CESM2_ssp245_r11i1p1f1_gn_20150101-20641231.nc may have an issue, or it may have been permanently moved to a new URL.'

#### Expected behavior

After clicking on 'Download the data file with http.', the file started downloading with the downloader on the Browser.

#### Screenshots
![1 (1)](https://github.com/esgf2-us/metagrid/assets/129763749/428bf78c-462c-44da-a3a0-3de70e5d3d84)
![1 (2)](https://github.com/esgf2-us/metagrid/assets/129763749/b00433a8-43f0-41bd-914c-f946a7106efe)

**Comment by sashakames** [comment]
Please write esgf-user@llnl.gov as the issue doesn't concern the web application but data hosted at a partner site.  Thanks!

**Comment by LangyaDavid** [comment]
> Please write [esgf-user@llnl.gov](mailto:esgf-user@llnl.gov) as the issue doesn't concern the web application but data hosted at a partner site. Thanks!

Thanks! I will try.
