### ISSUE TITLE
Wget button glitched in "Download Your Cart"

### ISSUE THREAD

**Issue by LangyaDavid** [esgf2-us/metagrid#645]
### Describe the bug

The button of wget download located in the bottom of the Cart page doesn't work. 
Sometimes it helps me download the wget script for the files I need when I enter the cart page for the first time of the day, and it just never work again for the rest of the time.

**Desktop (please complete the following information):**

- OS: Windows 10

- Browser and Version: Microsoft Edge Version 126.0.2592.61 (Official Build) (x86_64)

#### To Reproduce

1. Add 100 files into my cart.
2. Enter my cart and choose to show 100 files per page.
3. Select all 100 files in every page
4. Scroll down to the bottom and choose 'wget' for 'Download Your Cart'
5. Click on 'Download'
6. Nothing happens

#### Expected behavior

After clicking on 'Download' the browser should start downloading a wget script for all selected files.
#### Screenshots

![1718956210594](https://github.com/esgf2-us/metagrid/assets/129763749/c559fa78-e301-40d0-aa77-1672b08a3b86)

**Comment by sashakames** [comment]
(1) Can you try Chrome or Firefox?  Edge is not supported by the development team.  (2) I have found that logging out , back in (though the cart should persist) seems to fix the issue.  Also refresh the tab?

**Comment by LangyaDavid** [comment]
> (1) Can you try Chrome or Firefox? Edge is not supported by the development team. (2) I have found that logging out , back in (though the cart should persist) seems to fix the issue. Also refresh the tab?

Logging out seems to work! ( sometimes however, I still looking forward to the fixing of that button thus it will be much more convenient for downloading data~) 
Thanks for your assistance!

**Comment by sashakames** [comment]
I am reopening as a reminder to the development team that we would like the button to work without the workaround in Chrome and Firefox...

**Comment by sashakames** [comment]
Update: we have fixed this issue, being staged on https://esgf-dev1.llnl.gov/ note this is a test server and chance to be offline for frequent updates.

**Comment by sashakames** [comment]
Deployed on aims2.llnl.gov
