### ISSUE TITLE
There was an issue fetching search results. Please contact support or try again later.

### ISSUE THREAD

**Issue by alrdrop** [esgf2-us/metagrid#648]
### Describe the bug

**Desktop (please complete the following information):**Mac OS

- OS: 14.5 

- Browser and Version: Chrome

#### To Reproduce

1. Go to 'https://aims2.llnl.gov/search'
2. See error 'There was an issue fetching search results. Please contact support or try again later.'

#### Additional context

<It was working a few minutes ago. But it stopped working even when I tried and waited for more than 10 min, I also checked that this node is online.>

**Comment by sashakames** [comment]
Due to an issue with the search services, corrected now..
