### ISSUE TITLE
dkrz nodes down

### ISSUE THREAD

**Issue by iariailx** [esgf2-us/metagrid#653]
dkrz nodes have been down for over a day, been checking below for updates:

https://aims2.llnl.gov/nodes/

If I try to use aims3.llnl.gov, the link from above url gives: THREDDS catalogs are temporarily disabled

**Comment by sashakames** [comment]
The catalogs are permanently disabled.  If you are having an issue accessing data hosted at DKRZ please email esgf-user@llnl.gov so someone from that center can provide assistance.
