### ISSUE TITLE
CMIP5 variable filter

### ISSUE THREAD

**Issue by Florent-Co** [esgf2-us/metagrid#656]
The variable search filter does not seem to work for CMIP5 data

**Comment by sashakames** [comment]
For CMIP5 you need to use the "filename filter" at the bottom of the search pane.  While the datasets are indexed by the variables they include, all the variables available for a particular realm are part, eg if you search for tas, you'll get back the atmos datasets with all the variables.  instead put "tas" in the filename filter.
