### ISSUE TITLE
Unable to download the data

### ISSUE THREAD

**Issue by yu900** [esgf2-us/metagrid#660]
Unable to download the data, how to solve thank you
![屏幕截图 2024-09-19 223728](https://github.com/user-attachments/assets/f4119c10-b959-482f-a094-b512e907e7d3)
![屏幕截图 2024-09-19 224110](https://github.com/user-attachments/assets/bcf19fe8-1ccf-4202-8e74-7cbb04c4b81e)

**Comment by sashakames** [comment]
Thank you for reporting, we have corrected the expired certificate.
