### ISSUE TITLE
I get an Unknown Error with entering browser.

### ISSUE THREAD

**Issue by Gamja-helpme** [esgf2-us/metagrid#661]
### Describe the bug

When I entered the browser(https://aims2.llnl.gov/search), I got an Unknown Error and couldn't go to page 'Sign In'.
Yesterday, I put some datasets into a cart and off my computer. 
When I entered the brower, I got an Unknown Error and "please empty cart"(I don't remember exactly;). 
I went to 'Cart' page(including 10 datasets) but its loading was too long. 
After I deleted Chrome site records and cookies, I entered the brower again. 
And here's my situations: Unknown Error / 'Sign In' page is 'BAD GATEWAY' / 'Cart' page is empty
![1](https://github.com/user-attachments/assets/8c33da26-1afa-482c-8b73-d43caa262b87)
![2](https://github.com/user-attachments/assets/81b77796-3034-4a37-970a-1a9255a3e078)
![3](https://github.com/user-attachments/assets/7d75c45e-127b-4a2f-9d0d-af97f89b7300)

+I reboosted my system but it didn't work. 
What can I do?

**Desktop (please complete the following information):**

- OS: Windows 10

- Browser and Version: Google Chrome Version 129.0.6668.59 (Official Build) (x86_64)

#### To Reproduce

1.

**Comment by Fere225** [comment]
I have the same issue

**Comment by Fere225** [comment]
![image](https://github.com/user-attachments/assets/f8fe80d9-4306-40e1-8315-98eb51bf39cf)
![image](https://github.com/user-attachments/assets/a50357a9-fdbe-4cc2-85a6-b33952380365)
Did someone have a solution?

**Comment by sashakames** [comment]
Hi, for the pre-release you can try https://esgf-dev1.llnl.gov/  will have better functionality.
For an older stable release but several versions back you can try https://nimbus.llnl.gov/metagrid
We are working on a solution, but might not be working until next week.

**Comment by sashakames** [comment]
Sorry for the delay, the original link is now updated and functional again.
