### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by Sanghyup-Lee** [esgf2-us/metagrid#663]
### Describe the bug

After clicking the download button on a website, I was redirected to a new page displaying the message: "Service Unavailable: The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

**Desktop (please complete the following information):**

- OS: Windows 10 Enterprise

- Browser and Version: Google Chrome Version 129.0.6668.70 (Official Build) (64-bit)

#### To Reproduce

1. error site address: 
https://esgf-data03.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-H/highresSST-future/r1i1p1f1/day/hur/gn/v20200619/hur_day_MRI-AGCM3-2-H_highresSST-future_r1i1p1f1_gn_20150101-20151231.nc

#### Screenshots

![image](https://github.com/user-attachments/assets/dfa9e140-d3fc-46c9-89a7-50798d3926ad)

**Comment by sashakames** [comment]
This is a problem with the site hosting the data. Please email the support list [esgf-user@llnl.gov](mailto:esgf-user@llnl.gov)

**Comment by sashakames** [comment]
Actually appeared to be a temporary problem, the data appears to be available.
