### ISSUE TITLE
Typo "avaiable" vs available

### ISSUE THREAD

**Issue by durack1** [esgf2-us/metagrid#664]
### Describe the bug

In non-latest (deprecated) datasets, the standard blurb has a typo - "IMPORTANT! This dataset has been retracted and is no longer avaiable for download."

#### To Reproduce

1. browse [here](https://aims2.llnl.gov/search?project=input4MIPs&versionType=all&activeFacets=%7B%22mip_era%22%3A%22CMIP6Plus%22%2C%22institution_id%22%3A%22SOLARIS-HEPPA%22%7D) and 
2. see this
<img width="1193" alt="Screenshot 2024-10-02 at 1 55 33 PM" src="https://github.com/user-attachments/assets/31a6f693-e739-4bc2-8f96-db53fceedc8c">

#### Expected behavior

No typo

**Comment by sashakames** [comment]
This shows how one can miss something in plain sight for years...

**Comment by sashakames** [comment]
This will be available on aims2.llnl.gov shortly, been merged into master now.

**Comment by durack1** [comment]
Nice work gents, v1.2.0 looks shiny and typo-free!
![Screenshot 2024-10-23 at 12 00 57 PM](https://github.com/user-attachments/assets/a20ebae8-909e-496c-b7ad-ec0f5666843b)

**Comment by sashakames** [comment]
Deployed!  Ensure you refresh your tab / or start a new browser session to see the corrected spelling.
