### ISSUE TITLE
looking for CMIP6.ScenarioMIP.NCAR.CESM2.ssp370.r11i1p1f1.6hrLev.ta.gn 9  476.07 GB

### ISSUE THREAD

**Issue by dnyates** [esgf2-us/metagrid#666]
### Describe the bug

**Desktop (please complete the following information):**

- OS: Windows

- Browser and Version:  Google Chrome

#### To Reproduce
 This is just an attempt to generate a wget for this model. I am able to get the wget, but the files are all empty.
 CMIP6.ScenarioMIP.NCAR.CESM2.ssp370.r11i1p1f1.6hrLev.ta.gn 9  
there appears to be 
476.07 GB
#### Expected behavior

wget downloads 

#### Additional context

data fields are empty.

**Comment by sashakames** [comment]
This is a problem with the site hosting the data.  Please email the support list esgf-user@llnl.gov
