### ISSUE TITLE
TaiESM1 Global Transfer unavailable on ESGF MetaGrid

### ISSUE THREAD

**Issue by Alek-1** [esgf2-us/metagrid#667]
### TaiESM1 unavailable on [ESGF](https://esgf-metagrid.cloud.dkrz.de/search) or [ESGF-llnl.gov](https://aims2.llnl.gov/search) since last Friday the 11.10.2024

I am looking to download the 6hrLv surface pressure variables for TaiESM1. Unrelated to the Data node chosen, Globus Ready is unavailable. It seems like the node is down.

#### To Reproduce

1. Go to [ESGF](https://esgf-metagrid.cloud.dkrz.de/search)
2. Select the following options to get the datasets.
latest = true AND (source_id = TaiESM1) AND (variable_id = ps) AND (table_id = 6hrLev) AND (variant_label = r1i1p1f1) AND (experiment_id = historical OR ssp126 OR ssp245 OR ssp585 OR ssp370) AND (data_node = esgf.rcec.sinica.edu.tw)

![image](https://github.com/user-attachments/assets/584f75a5-77f8-46fe-baf6-5415a90bf271)

### Expected behaviour

The data from the Tai GCM is available.

**Comment by sashakames** [comment]
Hello, the data provider does not support Globus.  You'll need to stick with wget for those datasets.

**Comment by lamaliang** [comment]
Hello

Sorry, our ESGF does not support Globus. We will add this transfer method in CMIP7.

**Comment by Alek-1** [comment]
wget scripts is the way I am trying to download the data. Unfortunately, this does not work.

**Comment by lamaliang** [comment]
Sorry the late for reply. Due to our ESGF server had some problems. We will fixed
