### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by hogikyan** [esgf2-us/metagrid#673]
### Describe the bug

Several 'ta' files are bad/empty for piControl simulation

**Desktop (please complete the following information):**

- OS: Mac OSX

- Browser and Version: Google Chrome Version 129.0.6668.90

#### Expected behavior

Files download and contain data

#### Screenshots

example ncdump error:
         >> ncdump -h ta_Amon_CMCC-CM2-SR5_piControl_r1i1p1f1_gn_207501-209912.nc 
ncdump: ta_Amon_CMCC-CM2-SR5_piControl_r1i1p1f1_gn_207501-209912.nc: NetCDF: Unknown file format

**Comment by sashakames** [comment]
Please contact the esgf-user@llnl.gov list and provide information including the download url.
