### ISSUE TITLE
Missing file(s) depending on download method for ta, abrupt-4xCO2

### ISSUE THREAD

**Issue by hogikyan** [esgf2-us/metagrid#674]
### Describe the bug

Several 'ta' files are bad/empty for abrupt-4xCO2 simulation

**Desktop (please complete the following information):**

- OS: Mac OSX

- Browser and Version: Google Chrome Version 129.0.6668.90

#### Expected behavior

Files download and contain data

#### Screenshots

example ncdump error:
         >> ncdump -h ta_Amon_MPI-ESM-1-2-HAM_abrupt-4xCO2_r1i1p1f1_gn_195001-196912.nc
ncdump: ta_Amon_MPI-ESM-1-2-HAM_abrupt-4xCO2_r1i1p1f1_gn_195001-196912.nc: NetCDF: Unknown file format

**Comment by sashakames** [comment]
Please contact `esgf-user@llnl.gov` for data support.
