### ISSUE TITLE
Globus failure on ESGF website but Globus itself works well

### ISSUE THREAD

**Issue by tianyiqun997** [esgf2-us/metagrid#676]
I tried to use Globus on ESGF website but after everything all set, it gives me this error:

$ <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html> is your error. Please contact ESGF support.

The Globus itself still works well, I tried myself to transfer data on the server.

**Comment by sashakames** [comment]
We have deployed a fix to this issue.
