### ISSUE TITLE
Cant download any data from new esgf site

### ISSUE THREAD

**Issue by trashcanlicker08** [esgf2-us/metagrid#693]
Login button doesnt work, old openid credentials dont work. cant download anything. 
i tried to bypass the openid prompt, but it doesnt work. 

i desperately need to download those files for my thesis. what is going on? 

im working on macOS 13.7.1. the old page was just fine... why complicate things? and why is it that after month there is still no fix?

**Comment by skremdwd** [comment]
I am probably not the owner of the site or data you are looking for, but the information you are giving is not very detailed and not very helpful to find a solution, despite the slightly unkind undertone.

Which site or insititute are you referring to?
Which files/datasets do want to access?
Which "after a month" issue are you referring to? (Issue number...)
How do you try to access the data, via the Websites Download Link or wget Script?

Also: you may contact the operator of the site or the institute directly. This repository only contains a Open Source Stack and no datasets or login data, that is handled individually by the institute that is hosting the stack that contains the data you want to access.

**Comment by skremdwd** [comment]
I just saw that you commented in #659, so maybe discuss this issue there and close this duplicate one here.

**Comment by sashakames** [comment]
Duplicate...
